### ISSUE TITLE
Peer-to-Peer code review (Mike, Mahdi, Adesina)

### ISSUE THREAD

**Issue by mahdinoori2000** [khanh-devos/MyPortfolio#10]
**Mike's suggestion:**
- From Mike...Please try to use the social and other images after exporting them from Figma, just as these are used in Figma design template.

**Adesina's suggestion:**
- Kindly add JavaScript linter. Because it will check for errors in your JS code and you can solve it so easily with JS linter.

**Mahdi's suggestion:**
- Good job so far,  you did a great job.

**Comment by khanh-devos** [comment]
Yes, thank you. I think I have done it.
